# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 05:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20160505_2245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='is_favorite',
            new_name='is_favourite',
        ),
    ]
