# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 05:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20160505_2248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='date_reviewd',
            new_name='date_reviewed',
        ),
    ]
